import { PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import { IBM_Plex_Sans_Arabic } from 'next/font/google';

import './globals.css';

const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({ subsets: ['arabic', 'latin'], weight: ['400', '500', '600', '700'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={ibmPlexSansArabic.className}>{children}</body>
    </html>
  );
}
